title: Tutorial
author: marmoi
email: marmoi@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I will describe what I am going to talk about. Stay tuned 

# social links
twitter_username: no twitter # DO NOT include the @ character, or else the build will fail!
github_username:  marmoi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
